# Disable sudo to speed up the build
sudo: false

language: python
  "3.6"

cache: pip

# command to install dependencies 
before_script: 
  - easy_install distribute 
  - pip install -r requirements.txt 


# command to run tests 
script: 
  -python hello.py
